return {
    {
        "hyasysu/astroui",
        lazy = true,
        ---@type AstroUIOpts
        opts = {
            colorscheme = "astrotheme",
            icons = {
                ActiveLSP = "",
                ActiveTS = "",
                ArrowLeft = "",
                ArrowRight = "",
                Bookmarks = "",
                BufferClose = "󰅖",
                DapBreakpoint = "",
                DapBreakpointCondition = "",
                DapBreakpointRejected = "",
                DapLogPoint = "󰛿",
                DapStopped = "󰁕",
                Debugger = "",
                DefaultFile = "󰈙",
                Diagnostic = "󰒡",
                DiagnosticError = "",
                DiagnosticHint = "󰌵",
                DiagnosticInfo = "󰋼",
                DiagnosticWarn = "",
                Ellipsis = "…",
                Environment = "",
                FileNew = "",
                FileModified = "",
                FileReadOnly = "",
                FoldClosed = "",
                FoldOpened = "",
                FoldSeparator = " ",
                FolderClosed = "",
                FolderEmpty = "",
                FolderOpen = "",
                Git = "󰊢",
                GitAdd = "",
                GitBranch = "",
                GitChange = "",
                GitConflict = "",
                GitDelete = "",
                GitIgnored = "◌",
                GitRenamed = "➜",
                GitSign = "▎",
                GitStaged = "✓",
                GitUnstaged = "✗",
                GitUntracked = "★",
                List = "",
                LSPLoading1 = "",
                LSPLoading2 = "󰀚",
                LSPLoading3 = "",
                MacroRecording = "",
                Package = "󰏖",
                Paste = "󰅌",
                Refresh = "",
                Search = "",
                Selected = "❯",
                Session = "󱂬",
                Sort = "󰒺",
                Spellcheck = "󰓆",
                Tab = "󰓩",
                TabClose = "󰅙",
                Terminal = "",
                Window = "",
                WordFile = "󰈭",
            },
            text_icons = {
                ActiveLSP = "LSP:",
                ArrowLeft = "<",
                ArrowRight = ">",
                BufferClose = "x",
                DapBreakpoint = "B",
                DapBreakpointCondition = "C",
                DapBreakpointRejected = "R",
                DapLogPoint = "L",
                DapStopped = ">",
                DefaultFile = "[F]",
                DiagnosticError = "X",
                DiagnosticHint = "?",
                DiagnosticInfo = "i",
                DiagnosticWarn = "!",
                Ellipsis = "...",
                Environment = "Env:",
                FileModified = "*",
                FileReadOnly = "[lock]",
                FoldClosed = "+",
                FoldOpened = "-",
                FoldSeparator = " ",
                FolderClosed = "[D]",
                FolderEmpty = "[E]",
                FolderOpen = "[O]",
                GitAdd = "[+]",
                GitChange = "[/]",
                GitConflict = "[!]",
                GitDelete = "[-]",
                GitIgnored = "[I]",
                GitRenamed = "[R]",
                GitSign = "|",
                GitStaged = "[S]",
                GitUnstaged = "[U]",
                GitUntracked = "[?]",
                MacroRecording = "Recording:",
                Paste = "[PASTE]",
                Search = "?",
                Selected = "*",
                Spellcheck = "[SPELL]",
                TabClose = "X",
            },
            lazygit = {
                theme_path = vim.fs.normalize(vim.fn.stdpath "cache" .. "/astroui-lazygit-config.yml"),
                theme = {
                    [241] = { fg = "Special" },
                    activeBorderColor = { fg = "MatchParen", bold = true },
                    cherryPickedCommitBgColor = { bg = "Substitute" },
                    cherryPickedCommitFgColor = { fg = "Substitute" },
                    defaultFgColor = { fg = "Normal" },
                    inactiveBorderColor = { fg = "FloatBorder" },
                    markedBaseCommitBgColor = { bg = "CurSearch" },
                    markedBaseCommitFgColor = { fg = "CurSearch" },
                    optionsTextColor = { fg = "Function" },
                    searchingActiveBorderColor = { fg = "MatchParen", bold = true },
                    selectedLineBgColor = { bg = "Visual" }, -- set to `default` to have no background colour
                    unstagedChangesColor = { fg = "DiagnosticError" },
                },
            },
        },
    },
    {
        "hyasysu/astrocore",
        dependencies = { "hyasysu/astroui" },
        lazy = false,
        priority = 10000,
        opts = function(_, opts)
            local get_icon = require("astroui").get_icon
            return require("astrocore").extend_tbl(opts, {
                features = {
                    large_buf = { notify = true, size = 1.5 * 1024 * 1024, lines = 100000, line_length = 1000 }, -- set global limits for large files
                    autopairs = true, -- enable autopairs at start
                    cmp = true, -- enable completion at start
                    diagnostics_mode = 3, -- enable diagnostics by default
                    highlighturl = true, -- highlight URLs by default
                    notifications = true, -- disable notifications
                },
                diagnostics = {
                    virtual_text = true,
                    signs = {
                        text = {
                            [vim.diagnostic.severity.ERROR] = get_icon "DiagnosticError",
                            [vim.diagnostic.severity.HINT] = get_icon "DiagnosticHint",
                            [vim.diagnostic.severity.WARN] = get_icon "DiagnosticWarn",
                            [vim.diagnostic.severity.INFO] = get_icon "DiagnosticInfo",
                        },
                    },
                    update_in_insert = true,
                    underline = true,
                    severity_sort = true,
                    float = {
                        focused = false,
                        style = "minimal",
                        border = "rounded",
                        source = true,
                        header = "",
                        prefix = "",
                    },
                    -- TODO: remove check when dropping support for neovim v0.10
                    jump = vim.fn.has "nvim-0.11" == 1 and { float = true } or nil,
                },
                rooter = {
                    enabled = true,
                    detector = { "lsp", { ".git", "_darcs", ".hg", ".bzr", ".svn" }, { "lua", "MakeFile", "package.json" } },
                    ignore = {
                        servers = {},
                        dirs = {},
                    },
                    autochdir = false,
                    scope = "global",
                    notify = false,
                },
                sessions = {
                    autosave = { last = true, cwd = true },
                    ignore = {
                        dirs = {},
                        filetypes = { "gitcommit", "gitrebase" },
                        buftypes = {},
                    },
                },
            } --[[@as AstroCoreOpts]])
        end,
    }
}
